### PR TITLE
Return non-zero when tests fail

### PR DESCRIPTION
**Pull request by altendky**
This allows for shell scripts to check for success or failure without parsing
the printed output.  If the function name is later changed from main() it
will also allow other code calling the tests to also easily check the pass
or fail status.

### CODE REVIEW

**Comment by altendky** [comment]
@veorq, did you have any concerns about this that I should try to address?

**Comment by veorq** [comment]
> @veorq, did you have any concerns about this that I should try to address?

Looks good to me. The stdbool include being just to define `any_failed` as `bool` rather than `int` doesn't hurt but makes the code even less C89-compliant.

**Comment by altendky** [comment]
I figured the fixed width types everywhere already threw that out the window anyways.  Along with `--std=c99` in the `makefile` and readme.  If I've missed the intent then certainly adjustments can be made.

**Comment by veorq** [comment]
Nbd, it's just that there is not benefit from using bool here apart from the semantical aspect. We can leave it, that's fine, just want to be careful to keep the code clear and simple.

**Pull request merged**
